name=MC14489
version=0.0.1
author=Ignacy110
maintainer=Ignacy110
sentence=Arduino library for MC14489 Multi-Character LED Display/Lamp Driver
paragraph=This library allows microcontroller to use MC14489 Multi-Character LED Display/Lamp Driver.
category=Communication
url=https://github.com/Ignacy110/MC14489
architectures=*
