name=MC14489
version=1.0.0
author=Ignacy110
maintainer=Ignacy110
sentence=Arduino library for the MC14489 5-digit LED display driver
paragraph=This library allows a microcontroller to control the MC14489, a 5-digit LED display driver capable of driving multiple common cathode 7-segment displays.
category=Display
url=https://github.com/Ignacy110/MC14489
architectures=*
